# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 67ea6d8812cc642ed83d3b21d80c8bce5d91f6c1bdc4e11bef18a94bea343f0b58400ee24b0130830d93e905b50b6e2ef3c9628f4195cb42baab29f1f35ce74d

test:
  secret_key_base: 47f2d4949dab5a4d98760a77098bbd2f822047ef6373fce4268b36110c00430c92040f7dde557717b712a5d7dbc48ad6a78a255f221b40151aded629768e8969

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
